<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SeatsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('seats')->insert([
            ['id' => 1, 'studioID' => 1, 'seatnumber' => '1', 'seatrow' => 'A'],
            ['id' => 2, 'studioID' => 1, 'seatnumber' => '2', 'seatrow' => 'A'],
            ['id' => 3, 'studioID' => 1, 'seatnumber' => '3', 'seatrow' => 'A'],
            ['id' => 4, 'studioID' => 1, 'seatnumber' => '4', 'seatrow' => 'A'],
            ['id' => 5, 'studioID' => 1, 'seatnumber' => '5', 'seatrow' => 'A'],
            ['id' => 6, 'studioID' => 1, 'seatnumber' => '6', 'seatrow' => 'A'],
            ['id' => 7, 'studioID' => 1, 'seatnumber' => '7', 'seatrow' => 'A'],
            ['id' => 8, 'studioID' => 1, 'seatnumber' => '8', 'seatrow' => 'A'],
            ['id' => 9, 'studioID' => 1, 'seatnumber' => '9', 'seatrow' => 'A'],
            ['id' => 10, 'studioID' => 1, 'seatnumber' => '10', 'seatrow' => 'A'],
            ['id' => 11, 'studioID' => 1, 'seatnumber' => '1', 'seatrow' => 'B'],
            ['id' => 12, 'studioID' => 1, 'seatnumber' => '2', 'seatrow' => 'B'],
            ['id' => 13, 'studioID' => 1, 'seatnumber' => '3', 'seatrow' => 'B'],
            ['id' => 14, 'studioID' => 1, 'seatnumber' => '4', 'seatrow' => 'B'],
            ['id' => 15, 'studioID' => 1, 'seatnumber' => '5', 'seatrow' => 'B'],
            ['id' => 16, 'studioID' => 1, 'seatnumber' => '6', 'seatrow' => 'B'],
            ['id' => 17, 'studioID' => 1, 'seatnumber' => '7', 'seatrow' => 'B'],
            ['id' => 18, 'studioID' => 1, 'seatnumber' => '8', 'seatrow' => 'B'],
            ['id' => 19, 'studioID' => 1, 'seatnumber' => '9', 'seatrow' => 'B'],
            ['id' => 20, 'studioID' => 1, 'seatnumber' => '10', 'seatrow' => 'B'],
            ['id' => 21, 'studioID' => 1, 'seatnumber' => '1', 'seatrow' => 'C'],
            ['id' => 22, 'studioID' => 1, 'seatnumber' => '2', 'seatrow' => 'C'],
            ['id' => 23, 'studioID' => 1, 'seatnumber' => '3', 'seatrow' => 'C'],
            ['id' => 24, 'studioID' => 1, 'seatnumber' => '4', 'seatrow' => 'C'],
            ['id' => 25, 'studioID' => 1, 'seatnumber' => '5', 'seatrow' => 'C'],
            ['id' => 26, 'studioID' => 1, 'seatnumber' => '6', 'seatrow' => 'C'],
            ['id' => 27, 'studioID' => 1, 'seatnumber' => '7', 'seatrow' => 'C'],
            ['id' => 28, 'studioID' => 1, 'seatnumber' => '8', 'seatrow' => 'C'],
            ['id' => 29, 'studioID' => 1, 'seatnumber' => '9', 'seatrow' => 'C'],
            ['id' => 30, 'studioID' => 1, 'seatnumber' => '10', 'seatrow' => 'C'],
            ['id' => 31, 'studioID' => 1, 'seatnumber' => '1', 'seatrow' => 'D'],
            ['id' => 32, 'studioID' => 1, 'seatnumber' => '2', 'seatrow' => 'D'],
            ['id' => 33, 'studioID' => 1, 'seatnumber' => '3', 'seatrow' => 'D'],
            ['id' => 34, 'studioID' => 1, 'seatnumber' => '4', 'seatrow' => 'D'],
            ['id' => 35, 'studioID' => 1, 'seatnumber' => '5', 'seatrow' => 'D'],
            ['id' => 36, 'studioID' => 1, 'seatnumber' => '6', 'seatrow' => 'D'],
            ['id' => 37, 'studioID' => 1, 'seatnumber' => '7', 'seatrow' => 'D'],
            ['id' => 38, 'studioID' => 1, 'seatnumber' => '8', 'seatrow' => 'D'],
            ['id' => 39, 'studioID' => 1, 'seatnumber' => '9', 'seatrow' => 'D'],
            ['id' => 40, 'studioID' => 1, 'seatnumber' => '10', 'seatrow' => 'D'],

            ['id' => 41, 'studioID' => 2, 'seatnumber' => '1', 'seatrow' => 'A'],
            ['id' => 42, 'studioID' => 2, 'seatnumber' => '2', 'seatrow' => 'A'],
            ['id' => 43, 'studioID' => 2, 'seatnumber' => '3', 'seatrow' => 'A'],
            ['id' => 44, 'studioID' => 2, 'seatnumber' => '4', 'seatrow' => 'A'],
            ['id' => 45, 'studioID' => 2, 'seatnumber' => '5', 'seatrow' => 'A'],
            ['id' => 46, 'studioID' => 2, 'seatnumber' => '6', 'seatrow' => 'A'],
            ['id' => 47, 'studioID' => 2, 'seatnumber' => '7', 'seatrow' => 'A'],
            ['id' => 48, 'studioID' => 2, 'seatnumber' => '8', 'seatrow' => 'A'],
            ['id' => 49, 'studioID' => 2, 'seatnumber' => '9', 'seatrow' => 'A'],
            ['id' => 50, 'studioID' => 2, 'seatnumber' => '10', 'seatrow' => 'A'],
            ['id' => 51, 'studioID' => 2, 'seatnumber' => '1', 'seatrow' => 'B'],
            ['id' => 52, 'studioID' => 2, 'seatnumber' => '2', 'seatrow' => 'B'],
            ['id' => 53, 'studioID' => 2, 'seatnumber' => '3', 'seatrow' => 'B'],
            ['id' => 54, 'studioID' => 2, 'seatnumber' => '4', 'seatrow' => 'B'],
            ['id' => 55, 'studioID' => 2, 'seatnumber' => '5', 'seatrow' => 'B'],
            ['id' => 56, 'studioID' => 2, 'seatnumber' => '6', 'seatrow' => 'B'],
            ['id' => 57, 'studioID' => 2, 'seatnumber' => '7', 'seatrow' => 'B'],
            ['id' => 58, 'studioID' => 2, 'seatnumber' => '8', 'seatrow' => 'B'],
            ['id' => 59, 'studioID' => 2, 'seatnumber' => '9', 'seatrow' => 'B'],
            ['id' => 60, 'studioID' => 2, 'seatnumber' => '10', 'seatrow' => 'B'],
            ['id' => 61, 'studioID' => 2, 'seatnumber' => '1', 'seatrow' => 'C'],
            ['id' => 62, 'studioID' => 2, 'seatnumber' => '2', 'seatrow' => 'C'],
            ['id' => 63, 'studioID' => 2, 'seatnumber' => '3', 'seatrow' => 'C'],
            ['id' => 64, 'studioID' => 2, 'seatnumber' => '4', 'seatrow' => 'C'],
            ['id' => 65, 'studioID' => 2, 'seatnumber' => '5', 'seatrow' => 'C'],
            ['id' => 66, 'studioID' => 2, 'seatnumber' => '6', 'seatrow' => 'C'],
            ['id' => 67, 'studioID' => 2, 'seatnumber' => '7', 'seatrow' => 'C'],
            ['id' => 68, 'studioID' => 2, 'seatnumber' => '8', 'seatrow' => 'C'],
            ['id' => 69, 'studioID' => 2, 'seatnumber' => '9', 'seatrow' => 'C'],
            ['id' => 70, 'studioID' => 2, 'seatnumber' => '10', 'seatrow' => 'C'],
            ['id' => 71, 'studioID' => 2, 'seatnumber' => '1', 'seatrow' => 'D'],
            ['id' => 72, 'studioID' => 2, 'seatnumber' => '2', 'seatrow' => 'D'],
            ['id' => 73, 'studioID' => 2, 'seatnumber' => '3', 'seatrow' => 'D'],
            ['id' => 74, 'studioID' => 2, 'seatnumber' => '4', 'seatrow' => 'D'],
            ['id' => 75, 'studioID' => 2, 'seatnumber' => '5', 'seatrow' => 'D'],
            ['id' => 76, 'studioID' => 2, 'seatnumber' => '6', 'seatrow' => 'D'],
            ['id' => 77, 'studioID' => 2, 'seatnumber' => '7', 'seatrow' => 'D'],
            ['id' => 78, 'studioID' => 2, 'seatnumber' => '8', 'seatrow' => 'D'],
            ['id' => 79, 'studioID' => 2, 'seatnumber' => '9', 'seatrow' => 'D'],
            ['id' => 80, 'studioID' => 2, 'seatnumber' => '10', 'seatrow' => 'D'],

            ['id' => 81, 'studioID' => 3, 'seatnumber' => '1', 'seatrow' => 'A'],
            ['id' => 82, 'studioID' => 3, 'seatnumber' => '2', 'seatrow' => 'A'],
            ['id' => 83, 'studioID' => 3, 'seatnumber' => '3', 'seatrow' => 'A'],
            ['id' => 84, 'studioID' => 3, 'seatnumber' => '4', 'seatrow' => 'A'],
            ['id' => 85, 'studioID' => 3, 'seatnumber' => '5', 'seatrow' => 'A'],
            ['id' => 86, 'studioID' => 3, 'seatnumber' => '6', 'seatrow' => 'A'],
            ['id' => 87, 'studioID' => 3, 'seatnumber' => '7', 'seatrow' => 'A'],
            ['id' => 88, 'studioID' => 3, 'seatnumber' => '8', 'seatrow' => 'A'],
            ['id' => 89, 'studioID' => 3, 'seatnumber' => '9', 'seatrow' => 'A'],
            ['id' => 90, 'studioID' => 3, 'seatnumber' => '10', 'seatrow' => 'A'],
            ['id' => 91, 'studioID' => 3, 'seatnumber' => '1', 'seatrow' => 'B'],
            ['id' => 92, 'studioID' => 3, 'seatnumber' => '2', 'seatrow' => 'B'],
            ['id' => 93, 'studioID' => 3, 'seatnumber' => '3', 'seatrow' => 'B'],
            ['id' => 94, 'studioID' => 3, 'seatnumber' => '4', 'seatrow' => 'B'],
            ['id' => 95, 'studioID' => 3, 'seatnumber' => '5', 'seatrow' => 'B'],
            ['id' => 96, 'studioID' => 3, 'seatnumber' => '6', 'seatrow' => 'B'],
            ['id' => 97, 'studioID' => 3, 'seatnumber' => '7', 'seatrow' => 'B'],
            ['id' => 98, 'studioID' => 3, 'seatnumber' => '8', 'seatrow' => 'B'],
            ['id' => 99, 'studioID' => 3, 'seatnumber' => '9', 'seatrow' => 'B'],
            ['id' => 100, 'studioID' => 3, 'seatnumber' => '10', 'seatrow' => 'B'],
            ['id' => 101, 'studioID' => 3, 'seatnumber' => '1', 'seatrow' => 'C'],
            ['id' => 102, 'studioID' => 3, 'seatnumber' => '2', 'seatrow' => 'C'],
            ['id' => 103, 'studioID' => 3, 'seatnumber' => '3', 'seatrow' => 'C'],
            ['id' => 104, 'studioID' => 3, 'seatnumber' => '4', 'seatrow' => 'C'],
            ['id' => 105, 'studioID' => 3, 'seatnumber' => '5', 'seatrow' => 'C'],
            ['id' => 106, 'studioID' => 3, 'seatnumber' => '6', 'seatrow' => 'C'],
            ['id' => 107, 'studioID' => 3, 'seatnumber' => '7', 'seatrow' => 'C'],
            ['id' => 108, 'studioID' => 3, 'seatnumber' => '8', 'seatrow' => 'C'],
            ['id' => 109, 'studioID' => 3, 'seatnumber' => '9', 'seatrow' => 'C'],
            ['id' => 110, 'studioID' => 3, 'seatnumber' => '10', 'seatrow' => 'C'],
            ['id' => 111, 'studioID' => 3, 'seatnumber' => '1', 'seatrow' => 'D'],
            ['id' => 112, 'studioID' => 3, 'seatnumber' => '2', 'seatrow' => 'D'],
            ['id' => 113, 'studioID' => 3, 'seatnumber' => '3', 'seatrow' => 'D'],
            ['id' => 114, 'studioID' => 3, 'seatnumber' => '4', 'seatrow' => 'D'],
            ['id' => 115, 'studioID' => 3, 'seatnumber' => '5', 'seatrow' => 'D'],
            ['id' => 116, 'studioID' => 3, 'seatnumber' => '6', 'seatrow' => 'D'],
            ['id' => 117, 'studioID' => 3, 'seatnumber' => '7', 'seatrow' => 'D'],
            ['id' => 118, 'studioID' => 3, 'seatnumber' => '8', 'seatrow' => 'D'],
            ['id' => 119, 'studioID' => 3, 'seatnumber' => '9', 'seatrow' => 'D'],
            ['id' => 120, 'studioID' => 3, 'seatnumber' => '10', 'seatrow' => 'D'],
        ]);
    }
}
